// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace DBManager.Domains
{
    public partial class TblAccessControl
    {
        public TblAccessControl()
        {
            TblUser = new HashSet<TblUser>();
        }

        public int User_Level { get; set; }
        public string User_Desc { get; set; }
        public bool Setting { get; set; }
        public bool IO { get; set; }
        public bool Communication { get; set; }
        public bool Motion { get; set; }
        public bool User_Management { get; set; }

        public virtual ICollection<TblUser> TblUser { get; set; }
    }
}