// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace DBManager.Domains
{
    public partial class TblError
    {
        public DateTime Stop_Time { get; set; }
        public DateTime Start_Time { get; set; }
        public string Machine_ID { get; set; }
        public string Station { get; set; }
        public string Lot_Number { get; set; }
        public int Error_ID { get; set; }
        public string Error_Type { get; set; }
        public string Error_Desc { get; set; }
    }
}