// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace DBManager.Domains
{
    public partial class TblLot
    {
        public int Id { get; set; }
        public string Lot_Number { get; set; }
        public string Operator_ID { get; set; }
        public string Recipe { get; set; }
        public DateTime Start_Time { get; set; }
        public DateTime End_Time { get; set; }
        public int Total_Input { get; set; }
        public int Total_Output { get; set; }
    }
}