// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace DBManager.Domains
{
    public partial class TblOEEConfig
    {
        public int Id { get; set; }
        public double IdealCycleTime { get; set; }
        public TimeSpan ShiftStartTime { get; set; }
        public int ShiftCount { get; set; }
    }
}