// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace DBManager.Domains
{
    public partial class TblOEE
    {
        public DateTime OEEDateTime { get; set; }
        public double Availability { get; set; }
        public double Performance { get; set; }
        public double Quality { get; set; }
        public double OEE { get; set; }
        public int ShiftNo { get; set; }
        public int PlannedProductionTime { get; set; }
        public double UnplannedDownTime { get; set; }
        public double PlannedDownTime { get; set; }
        public double RunTime { get; set; }
        public double IdealCycleTime { get; set; }
        public int TotalInput { get; set; }
        public int TotalOutput { get; set; }
    }
}