// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace DBManager.Domains
{
    public partial class TblRecipe
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public int Loop_Count { get; set; }
        public int Interval_Distance { get; set; }
        public double Interval_Delay { get; set; }
    }
}