// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace DBManager.Domains.Configurations
{
    public partial class TblAccessControlConfiguration : IEntityTypeConfiguration<TblAccessControl>
    {
        public void Configure(EntityTypeBuilder<TblAccessControl> entity)
        {
            entity.HasKey(e => e.User_Level)
                .HasName("PK_Tbl_AccessControl");

            entity.Property(e => e.User_Level).ValueGeneratedNever();

            entity.Property(e => e.User_Desc)
                .IsRequired()
                .HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblAccessControl> entity);
    }
}
