// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace DBManager.Domains.Configurations
{
    public partial class TblErrorConfiguration : IEntityTypeConfiguration<TblError>
    {
        public void Configure(EntityTypeBuilder<TblError> entity)
        {
            entity.HasKey(e => e.Stop_Time)
                .HasName("PK_Tbl_Error");

            entity.Property(e => e.Error_Desc)
                .IsRequired()
                .HasMaxLength(128);

            entity.Property(e => e.Error_Type)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Lot_Number)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Machine_ID)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Station)
                .IsRequired()
                .HasMaxLength(64);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblError> entity);
    }
}
