// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace DBManager.Domains.Configurations
{
    public partial class TblLotConfiguration : IEntityTypeConfiguration<TblLot>
    {
        public void Configure(EntityTypeBuilder<TblLot> entity)
        {
            entity.Property(e => e.Lot_Number)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Operator_ID)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Recipe)
                .IsRequired()
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblLot> entity);
    }
}
