// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace DBManager.Domains.Configurations
{
    public partial class TblOEEConfigConfiguration : IEntityTypeConfiguration<TblOEEConfig>
    {
        public void Configure(EntityTypeBuilder<TblOEEConfig> entity)
        {
            entity.HasKey(e => e.Id);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblOEEConfig> entity);
    }
}
