// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace DBManager.Domains.Configurations
{
    public partial class TblRecipeConfiguration : IEntityTypeConfiguration<TblRecipe>
    {
        public void Configure(EntityTypeBuilder<TblRecipe> entity)
        {
            entity.Property(e => e.Product_Name)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Loop_Count)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Interval_Distance)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Interval_Delay)
                .IsRequired()
                .HasMaxLength(50);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblRecipe> entity);
    }
}
