namespace GreatechApp.Core.Enums
{
    public enum CardNo : int
    {
        Card1 = 0,
    }

    public enum AxisNo : int
    {
        //Card 1
        IndexingMotor = 0,
        TapeSealMotor,
        Output_Dummy_Motor,
        Prober_Motor_1,
        Precisor1_Motor,
        Rotator_Motor,
        Prober_Motor_2,
        Prober_Motor_3,
        LinearPnPInput_ZMotor,
        LinearPnPInput_XMotor,
        Axis10_Spare,
        Axis11_Spare,
        NestShuttleInput_X1Motor,
        NestShuttleInput_X2Motor,
        NestShuttleOutput_X1Motor,
        NestShuttleOutput_X2Motor,
        PickNPlace_B_Turn,
        PickNPlace_B_Link,
        PickNPlace_A_Turn,
        PickNPlace_A_Link,
        PickNPlace_C_Turn,
        PickNPlace_C_Link,
        Axis22_Spare,
        Axis23_Spare,
        Axis24_Spare,
        InputLoader_TrayLifter,
        InputLoader_RightTrackMotor,
        InputLoader_LeftTrackMotor,
        InputLoader_BarcodeScannerMotor,
        InputLoader_EmptyTrayElevatorMotor,
        Axis30_Spare,
        Input_Dummy_Motor,

        //Card 2
        RotaryTable_12 = 64,
        RotaryTable_10,
        RotaryTable_12B,
        MT_Pusher_NestShuttleIn,
        MT_Pusher_Precisor1,
        MT_Pusher_Rotator,
        MT_Pusher_RotaryTable12,
        MT_Pusher_RotaryTable10,
        MT_Pusher_Precisor2,
        MT_Pusher_Vision1_LeftRight,
        MT_Pusher_Vision2_FrontBack,
        MT_Pusher_Vision3_Bottom,
        MT_Pusher_RotaryTable12B,
        MT_Pusher_Precisor3,
        MT_Pusher_TapeReel1,
        MT_Pusher_TapeReel2,
        OutputTray1_ElevatorMotor,
        OutputTray2_ElevatorMotor,
        OutputTray3_ElevatorMotor,
        Axis83_Spare,
        OutputTray1_LeftTrackMotor,
        OutputTray1_RightTrackMotor,
        OutputTray1_TopMotor,
        OutputTray1_BotMotor,
        LinearPnPOutput_ZMotor,
        OutputTray2_TopMotor,
        OutputTray2_BotMotor,
        OutputTray2_LeftTrackMotor,
        OutputTray2_RightTrackMotor,
        LinearPnPOutput_XMotor,
        OutputTray3_LeftTrackMotor,
        OutputTray3_RightTrackMotor,
        OutputTray3_TopMotor,
        OutputTray3_BotMotor,
        Axis98_Spare,
        Axis99_Spare,
    }

    public enum Ax_Motion_IO : uint
    {
        AX_MOTION_IO_RDY = 1,
        AX_MOTION_IO_ALM = 2,
        AX_MOTION_IO_LMTP = 4,
        AX_MOTION_IO_LMTN = 8,
        AX_MOTION_IO_ORG = 16,
        AX_MOTION_IO_DIR = 32,
        AX_MOTION_IO_EMG = 64,
        AX_MOTION_IO_PCS = 128,
        AX_MOTION_IO_ERC = 256,
        AX_MOTION_IO_EZ = 512,
        AX_MOTION_IO_CLR = 1024,
        AX_MOTION_IO_LTC = 2048,
        AX_MOTION_IO_SD = 4096,
        AX_MOTION_IO_INP = 8192,
        AX_MOTION_IO_SVON = 16384,
        AX_MOTION_IO_ALRM = 32768,
        AX_MOTION_IO_SLMTP = 65536,
        AX_MOTION_IO_SLMTN = 131072,
        AX_MOTION_IO_CMP = 262144,
        AX_MOTION_IO_CAMDO = 524288,
        AX_MOTION_IO_MAXTORLMT = 1048576
    }


    public enum MainTurretHead : int
    {
        MT_Pusher_NestShuttleIn = 0,
        MT_Pusher_Precisor1,
        MT_Pusher_Rotator,
        MT_Pusher_RotaryTable12,
        MT_Pusher_RotaryTable10,
        MT_Pusher_Vision1_LeftRight,
        MT_Pusher_Vision2_FrontBack,
        MT_Pusher_Vision3_Bottom,
        MT_Pusher_RotaryTable12B,
        MT_Pusher_TapeReel1,
        MT_Pusher_TapeReel2,
        Precisor1,
        Rotator,
    }

    public enum RotaryTable : int
    {
        RotaryTable12 = 0,
        RotaryTable10,
        RotaryTable12B,
    }

    public enum PNPTurn : int
    {
        PickNPlace_A_Turn = 0,
        PickNPlace_B_Turn,
        PickNPlace_C_Turn,
    }

    public enum PNPLink : int
    {
        PickNPlace_A_Link = 0,
        PickNPlace_B_Link,
        PickNPlace_C_Link,
    }

    public enum InputLoader : int
    {
        InputLoader_TrayLifter = 0,
        InputLoader_RightTrackMotor,
        InputLoader_LeftTrackMotor,
        InputLoader_BarcodeScannerMotor,
        InputLoader_EmptyTrayElevatorMotor,
    }

    public enum LinearPnPInput : int
    {
        LinearPnPInput_ZMotor = 0,
        LinearPnPInput_XMotor,
    }

    public enum OutputLoader : int
    {
        OutputTray1_ElevatorMotor = 0,
        OutputTray2_ElevatorMotor,
        OutputTray3_ElevatorMotor,
        OutputTray1_TopMotor,
        OutputTray2_TopMotor,
        OutputTray3_TopMotor,
        OutputTray1_LeftTrackMotor,
        OutputTray1_RightTrackMotor,
        OutputTray2_LeftTrackMotor,
        OutputTray2_RightTrackMotor,
        OutputTray3_LeftTrackMotor,
        OutputTray3_RightTrackMotor,
        OutputTray1_BotMotor,
        OutputTray2_BotMotor,
        OutputTray3_BotMotor,
    }

    public enum LinearPnPOutput : int
    {
        LinearPnPOutput_ZMotor = 0,
        LinearPnPOutput_XMotor,
    }

    public struct MotionIO
    {
        public bool Alarm;
        public bool PositifLimit;
        public bool NegativeLimit;
        public bool ServoOn;
        public bool Ready;
        public bool InPos;
    }

    public enum PCIConfig : int
    {
        Name = 0,
        Active,
        IOUpdate,
        ConversianValue,
        ConversianType,
        Speed,
        Acc,
        Dcc,
    }

    public enum PropertyID : uint
    {
        FT_DevIpoTypeMap = 0,
        FT_DevAxesCount = 1,
        FT_DevFunctionMap = 2,
        FT_DevOverflowCntr = 3,
        FT_MasCyclicCnt_R0 = 4,
        FT_MasCyclicCnt_R1 = 5,
        FT_DevMDAQTypeMap = 6,
        FT_DevMDAQTrigMap = 7,
        FT_DevMDAQMaxChan = 8,
        FT_DevMDAQMaxBufCount = 9,
        FT_DevLTCBufMaxCount = 10,
        FT_DevVersion = 11,
        FT_DevEmgMap = 12,
        FT_DevSupportAxesCount = 13,
        FT_AresVariableCount = 14,
        FT_AresSupportProcessCount = 15,
        FT_ECAT_Version = 16,
        FT_DaqDiMaxChan = 50,
        FT_DaqDoMaxChan = 51,
        FT_DaqAiRangeMap = 52,
        FT_DaqAoRangeMap = 53,
        FT_DaqAiMaxSingleChan = 54,
        FT_DaqAiMaxDiffChan = 55,
        FT_DaqAiResolution = 56,
        FT_DaqAoMaxChan = 57,
        FT_DaqAoResolution = 58,
        FT_DaqCntMaxChan = 59,
        CFG_DevBoardID = 201,
        CFG_DevRingID = 202,
        CFG_DevBaseAddress = 203,
        CFG_DevInterrupt = 204,
        CFG_DevBusNumber = 205,
        CFG_DevSlotNumber = 206,
        CFG_DevDriverVersion = 207,
        CFG_DevDllVersion = 208,
        CFG_DevComQualityContiErr = 209,
        CFG_DevComQualityErrRate = 210,
        CFG_DevComWdgMode = 211,
        CFG_DevFwMemory = 212,
        CFG_DevEmgReact = 213,
        CFG_DevFwVersion = 214,
        CFG_DevBelongsTo = 215,
        CFG_DevMasterDev = 216,
        CFG_DevSlaveDevs = 217,
        CFG_DevCPLDVersion = 218,
        CFG_DevCPLD_1Version = 219,
        CFG_DevEmgLogic = 220,
        CFG_DevLatestFwVersion = 221,
        CFG_DevEmgFilterTime = 222,
        CFG_DevMultiCmpAxisEnable = 223,
        CFG_DevMultiCmpOutChannel = 224,
        CFG_DevMultiCmpPulseLogic = 225,
        CFG_DevMultiCmpPulseWidth = 226,
        CFG_DevKillDec = 227,
        CFG_DevFuncDiFltSmpRate = 228,
        CFG_DevLogMsg = 229,
        CFG_DevErrorReact = 230,
        CFG_DevCompensateTableEnable = 231,
        CFG_MasBaudRate_R0 = 232,
        CFG_MasBaudRate_R1 = 233,
        CFG_MasComErrRate_R0 = 234,
        CFG_MasComErrRate_R1 = 235,
        CFG_MasComContiErr_R0 = 236,
        CFG_MasComContiErr_R1 = 237,
        CFG_MasIoComContiErr_R0 = 238,
        CFG_MasIoComContiErr_R1 = 239,
        CFG_MasDataComContiErr_R0 = 240,
        CFG_MasDataComContiErr_R1 = 241,
        CFG_DaqAiChanType = 251,
        CFG_DaqAiRanges = 252,
        CFG_DaqMaiRanges = 253,
        CFG_DaqAoRanges_C0 = 254,
        CFG_DaqAoRanges_C1 = 255,
        CFG_DaqAoRanges_C2 = 256,
        CFG_DaqAoRanges_C3 = 257,
        CFG_DaqAiGain = 258,
        CFG_MasCycleTime = 261,
        CFG_IoCycleTime = 262,
        CFG_DevMotionMasterShiftTime = 263,
        CFG_DevIoMasterShiftTime = 264,
        CFG_DevMultiTrigFifoWriteEnable = 265,
        CFG_DevMultiTrigPulseMode = 266,
        CFG_DevMultiTrigPWMFreq = 267,
        CFG_DevMultiTrigPWMDuty = 268,
        CFG_DevMultiTrigAutoEmptyEn = 269,
        CFG_DevMultiTrigForcePWMCount = 270,
        CFG_DevMotionLostFrameThreshold = 271,
        CFG_DevIOLostFrameThreshold = 272,
        CFG_DevMotionDisconnectEventTime = 273,
        CFG_DevIoDisconnectEventTime = 274,
        CFG_DevConfigurePDOs = 275,
        CFG_DevMultiCmpAxisEnableEx = 276,
        CFG_DevMultiCmpOutChannelEx = 277,
        CFG_DevMotionDisconnectSlave = 278,
        CFG_DevIoDisconnectSlave = 279,
        CFG_DevExtEncoderEn = 281,
        CFG_DevExtEncoderPPUNum = 282,
        CFG_DevExtEncoderPPUDemo = 283,
        CFG_DevExtEncoderLogic = 284,
        CFG_DevExtEncoderChannel = 285,
        CFG_DevMotionWarnThreshold = 291,
        CFG_DevMotionDisconnectFlag = 292,
        CFG_DevIoWarnThreshold = 293,
        CFG_DevIoDisconnectFlag = 294,
        CFG_DevMotionRescanTime = 295,
        CFG_DevIoRescanTime = 296,
        FT_AxFunctionMap = 301,
        FT_AxMaxVel = 302,
        FT_AxMaxAcc = 303,
        FT_AxMaxDec = 304,
        FT_AxMaxJerk = 305,
        FT_AxPulseInMap = 306,
        FT_AxPulseInModeMap = 307,
        FT_AxPulseOutMap = 308,
        FT_AxPulseOutModeMap = 309,
        FT_AxAlarmMap = 310,
        FT_AxInpMap = 311,
        FT_AxErcMap = 312,
        FT_AxErcEnableModeMap = 313,
        FT_AxErcOnTimeMap = 314,
        FT_AxErcOffTimeMap = 315,
        FT_AxSdMap = 316,
        FT_AxElMap = 317,
        FT_AxSwMelMap = 318,
        FT_AxSwPelMap = 319,
        FT_AxHomeMap = 320,
        FT_AxBackLashMap = 321,
        FT_AxVibrationMap = 322,
        FT_AxAlmMap = 323,
        FT_AxCompareMap = 324,
        FT_AxLatchMap = 325,
        FT_AxCamDOMap = 326,
        FT_AxExtDriveMap = 327,
        FT_AxExtMasterSrcMap = 328,
        FT_AxGenDOMap = 329,
        FT_AxGenDIMap = 330,
        FT_AxSimStartSourceMap = 331,
        FT_AxHomeModeMap = 332,
        FT_AxIN1Map = 333,
        FT_AxIN2Map = 334,
        FT_AxIN3Map = 335,
        FT_AxIN4Map = 336,
        FT_AxIN5Map = 337,
        FT_AxDIFilterTimeMap = 338,
        FT_AxJogMap = 339,
        PAR_AxVelLow = 401,
        PAR_AxVelHigh = 402,
        PAR_AxAcc = 403,
        PAR_AxDec = 404,
        PAR_AxJerk = 405,
        PAR_AxHomeExMode = 406,
        PAR_AxHomeExSwitchMode = 407,
        PAR_AxHomeCrossDistance = 408,
        PAR_AxJerkL = 409,
        PAR_AxJogVelLow = 410,
        PAR_AxJogVelHigh = 411,
        PAR_AxJogAcc = 412,
        PAR_AxJogDec = 413,
        PAR_AxJogJerk = 414,
        PAR_AxHomeVelLow = 415,
        PAR_AxHomeVelHigh = 416,
        PAR_AxHomeAcc = 417,
        PAR_AxHomeDec = 418,
        PAR_AxHomeJerk = 419,
        PAR_AxJerkFactor = 443,
        PAR_AxHomeJerkFactor = 444,
        PAR_AxTargetPosition = 445,
        PAR_AxTargetVelocity = 446,
        PAR_AxTargetTorque = 447,
        PAR_AxControlWord = 448,
        PAR_AxStatusWord = 449,
        PAR_AxOperationMode = 450,
        PAR_AxMinAcc = 451,
        CFG_AxHomeDir = 484,
        CFG_AxHomePosition = 486,
        CFG_AxPPU = 551,
        CFG_AxPhyID = 552,
        CFG_AxMaxVel = 553,
        CFG_AxMaxAcc = 554,
        CFG_AxMaxDec = 555,
        CFG_AxMaxJerk = 556,
        CFG_AxPulseInMode = 557,
        CFG_AxPulseInLogic = 558,
        CFG_AxPulseInSource = 559,
        CFG_AxPulseOutMode = 560,
        CFG_AxAlmEnable = 561,
        CFG_AxAlmLogic = 562,
        CFG_AxAlmReact = 563,
        CFG_AxInpEnable = 564,
        CFG_AxInpLogic = 565,
        CFG_AxErcLogic = 566,
        CFG_AxErcOnTime = 567,
        CFG_AxErcOffTime = 568,
        CFG_AxErcEnableMode = 569,
        CFG_AxSdEnable = 570,
        CFG_AxSdLogic = 571,
        CFG_AxSdReact = 572,
        CFG_AxSdLatch = 573,
        CFG_AxElEnable = 574,
        CFG_AxElLogic = 575,
        CFG_AxElReact = 576,
        CFG_AxSwMelEnable = 577,
        CFG_AxSwPelEnable = 578,
        CFG_AxSwMelReact = 579,
        CFG_AxSwPelReact = 580,
        CFG_AxSwMelValue = 581,
        CFG_AxSwPelValue = 582,
        CFG_AxOrgEnable = 588,
        CFG_AxOrgLogic = 589,
        CFG_AxEzEnable = 590,
        CFG_AxEzLogic = 591,
        CFG_AxEzCount = 592,
        CFG_AxBacklashEnable = 593,
        CFG_AxBacklashPulses = 594,
        CFG_AxVibrationEnable = 595,
        CFG_AxVibrationReverseTime = 596,
        CFG_AxVibrationForwardTime = 597,
        CFG_AxPositionLagEn = 598,
        CFG_AxMaxPositionLag = 599,
        CFG_AxEmgReaction = 600,
        CFG_AxLatchLogic = 601,
        CFG_AxHomeResetEnable = 602,
        CFG_AxCmpSrc = 603,
        CFG_AxCmpMethod = 604,
        CFG_AxCmpPulseMode = 605,
        CFG_AxCmpPulseLogic = 606,
        CFG_AxCmpPulseWidth = 607,
        CFG_AxCmpEnable = 608,
        CFG_AxRange = 609,
        CFG_AxGenDoEnable = 610,
        CFG_AxExtMasterSrc = 611,
        CFG_AxExtSelEnable = 612,
        CFG_AxExtPulseNum = 613,
        CFG_AxOrgLatch = 614,
        CFG_AxOutLogic = 615,
        CFG_AxDirLogic = 616,
        CFG_AxExtPulseInMode = 617,
        CFG_AxExtPresetNum = 618,
        CFG_AxErcOffTmEnable = 619,
        CFG_AxAuxOutEnable = 620,
        CFG_AxAuxOutTime = 621,
        CFG_AxCamDOEnable = 622,
        CFG_AxCamDOLoLimit = 623,
        CFG_AxCamDOHiLimit = 624,
        CFG_AxCamDOMode = 625,
        CFG_AxCamDODir = 626,
        CFG_AxCamDOCmpSrc = 627,
        CFG_AxCamDOLogic = 628,
        CFG_AxModuleRange = 629,
        CFG_AxBacklashVel = 630,
        CFG_AxLatchEnable = 631,
        CFG_AxPulseInMaxFreq = 632,
        CFG_AxSimStartSource = 633,
        CFG_AxOrgReact = 634,
        CFG_AxIN1StopEnable = 635,
        CFG_AxIN1StopReact = 636,
        CFG_AxIN1StopLogic = 637,
        CFG_AxIN2StopEnable = 638,
        CFG_AxIN2StopReact = 639,
        CFG_AxIN2StopLogic = 640,
        CFG_AxIN4StopEnable = 641,
        CFG_AxIN4StopReact = 642,
        CFG_AxIN4StopLogic = 643,
        CFG_AxIN5StopEnable = 644,
        CFG_AxIN5StopReact = 645,
        CFG_AxIN5StopLogic = 646,
        CFG_AxLatchBufEnable = 647,
        CFG_AxLatchBufMinDist = 648,
        CFG_AxLatchBufEventNum = 649,
        CFG_AxLatchBufSource = 650,
        CFG_AxLatchBufAxisID = 651,
        CFG_AxLatchBufEdge = 652,
        CFG_AxHomeOffsetDistance = 653,
        CFG_AxHomeOffsetVel = 654,
        CFG_AxPWMFreq = 655,
        CFG_AxPWMDuty = 656,
        CFG_AxPPUDenominator = 657,
        CFG_AxGantryMaxDiffValue = 658,
        CFG_AxPelToleranceEnable = 666,
        CFG_AxPelToleranceValue = 667,
        CFG_AxSwPelToleranceEnable = 668,
        CFG_AxSwPelToleranceValue = 669,
        CFG_AxCmpPulseWidthEx = 670,
        CFG_AxMelToleranceEnable = 671,
        CFG_AxMelToleranceValue = 672,
        CFG_AxSwMelToleranceEnable = 673,
        CFG_AxSwMelToleranceValue = 674,
        CFG_AxALMFilterTime = 675,
        CFG_AxLMTPFilterTime = 676,
        CFG_AxLMTNFilterTime = 677,
        CFG_AxIN1FilterTime = 678,
        CFG_AxIN2FilterTime = 679,
        CFG_AxORGFilterTime = 680,
        CFG_AxIN4FilterTime = 681,
        CFG_AxIN5FilterTime = 682,
        CFG_AxEncoderRatio = 683,
        CFG_AxMaxErrCount = 684,
        CFG_AxResponseTime = 685,
        CFG_AxMaxCorrectTimes = 686,
        CFG_AxMultiCmpDeviation = 687,
        CFG_AxForcePWMOutTime = 688,
        CFG_AxLatchStopEnable = 689,
        CFG_AxLatchStopReact = 690,
        CFG_AxPulseStopSrc = 691,
        CFG_AxJogVLTime = 692,
        CFG_AxPulseOutReverse = 693,
        CFG_AxKillDec = 694,
        CFG_AxJogVelLow = 695,
        CFG_AxJogVelHigh = 696,
        CFG_AxJogAcc = 697,
        CFG_AxJogDec = 698,
        CFG_AxJogJerk = 699,
        CFG_AxMaxErrorCnt = 700,
        CFG_AxCounterMax = 701,
        PAR_GpVelLow = 701,
        CFG_AxOverflowMode = 702,
        PAR_GpVelHigh = 702,
        CFG_AxGantryActDiffValue = 703,
        PAR_GpAcc = 703,
        CFG_AxPelLogic = 704,
        PAR_GpDec = 704,
        CFG_AxMelLogic = 705,
        PAR_GpJerk = 705,
        CFG_AxSetCmpDO = 706,
        PAR_GpGroupID = 706,
        CFG_AxMPGOffsetEnable = 707,
        PAR_GpJerkL = 707,
        CFG_AxMPGOffsetSum = 708,
        PAR_GpIsPathDec = 708,
        CFG_AxIN1StopEdge = 709,
        PAR_GpRefPlane = 709,
        CFG_AxIN2StopEdge = 710,
        PAR_GpJerkFactor = 710,
        CFG_AxIN4StopEdge = 711,
        CFG_AxIN5StopEdge = 712,
        CFG_AxIN1OffsetValue = 713,
        CFG_AxIN2OffsetValue = 714,
        CFG_AxIN4OffsetValue = 715,
        CFG_AxIN5OffsetValue = 716,
        CFG_AxMPGMaxVel = 717,
        CFG_AxMPGAcc = 718,
        CFG_AxMPGDec = 719,
        CFG_AxMPGStopReact = 720,
        CFG_AxJogPAssign = 721,
        CFG_AxJogNAssign = 722,
        CFG_AxCamDOAssign = 723,
        CFG_AxIN1StopAssign = 724,
        CFG_AxAxTorqueConstData = 725,
        CFG_AxTorqueEnable = 726,
        CFG_AxJogJerkFactor = 727,
        CFG_AxDIStartTime = 728,
        CFG_AxDIStartEdge = 729,
        CFG_AxHomeORGSide = 730,
        CFG_AxCompensateEnable = 731,
        CFG_AxCmpTrigPathEnable = 732,
        CFG_AxCounterMin = 733,
        CFG_AxMaxTorque = 734,
        CFG_AxMaxMotorSpeed = 735,
        CFG_AxSvOnLogic = 736,
        CFG_AxGantryCompFactor = 738,
        CFG_AxRstLogic = 739,
        CFG_AxRstOn = 740,
        CFG_AxErcOn = 741,
        CFG_GpMaxVel = 801,
        CFG_GpMaxAcc = 802,
        CFG_GpMaxDec = 803,
        CFG_GpMaxJerk = 804,
        CFG_GpPPU = 805,
        CFG_GpAxesInGroup = 806,
        CFG_GpGroupID = 807,
        CFG_GpBldTime = 808,
        CFG_GpSFEnable = 809,
        CFG_GpVectorEnable = 814,
        CFG_GpSpdFwdVelEn = 815,
        CFG_GpSFMinAngle = 816,
        CFG_GpSFMaxAngle = 817,
        CFG_GpSFSpeedRatio = 818,
        CFG_GpSFMinCornerTime = 819,
        CFG_GpAxesInGroupEx = 820,
        CFG_GpPWMLinkVel = 821,
        CFG_GpPWMMonitorMode = 822,
        CFG_GpPWMRefVel = 823,
        PAR_RbVelLow = 1000,
        PAR_RbVelHigh = 1001,
        PAR_RbAcc = 1002,
        PAR_RbDec = 1003,
        PAR_RbJerk = 1004,
        PAR_RbRefPlane = 1005,
        CFG_RbLengthArm1 = 1200,
        CFG_RbLengthArm2 = 1201,
        CFG_RbLengthArm3 = 1202,
        CFG_RbHandMode = 1203,
        CFG_RbSFEnable = 1204,
        CFG_RbLengthArm4 = 1205,
        CFG_RbLengthArm5 = 1206,
        CFG_RbCSys = 1207,
        CFG_RbJogAxis = 1208,
        CFG_RbRZCOUPLING = 1209,
        CFG_RbRZCFNumerator = 1210,
        CFG_RbRZCFDenominator = 1211,
        CFG_RbScaraAxisMode = 1212,
        CFG_RbJ1J2CouplingEn = 1213,
        CFG_RbMoveLinkCSAngle = 1214,
        CFG_RbMoveLinkAutoEn = 1215,
        CFG_CH_DaqDiInvertEnable = 1500,
        CFG_CH_DaqDiLowFilter = 1501,
        CFG_CH_DaqDiHighFilter = 1502,
        CFG_CH_DaqDoFsvEnable = 1503,
        CFG_CH_DaqAoRange = 1504,
        CFG_CH_DaqAiRange = 1505,
        CFG_CH_DaqAiEnable = 1506,
        CFG_CH_DaqAiIntegrationTime = 1507,
        CFG_CH_DaqAoFsv = 1508,
        CFG_CH_DaqAoStartup = 1509,
        CFG_CH_DaqCntEnable = 1510,
        CFG_CH_DaqCntPulseInMode = 1511,
        CFG_CH_DaqCntInitValue = 1512,
        CFG_CH_DaqCntMaxValue = 1513,
        CFG_CH_DaqCntOverflowMode = 1514,
        CFG_CH_DaqCntLatchEnable = 1515,
        CFG_CH_DaqCntLatchEdge = 1516,
        CFG_CH_DaqCntCmpEnable = 1517,
        CFG_CH_DaqCntCmpMethod = 1518,
        CFG_CH_DaqCntCmpPulseEnable = 1519,
        CFG_CH_DaqCntCmpPulseMode = 1520,
        CFG_CH_DaqCntCmpPulseLogic = 1521,
        CFG_CH_DaqCntCmpPulseWidth = 1522,
        CFG_CH_DaqAoEnable = 1523
    }

    public enum HomeMode : uint
    {
        MODE1_Abs = 0,
        MODE2_Lmt = 1,
        MODE3_Ref = 2,
        MODE4_Abs_Ref = 3,
        MODE5_Abs_NegRef = 4,
        MODE6_Lmt_Ref = 5,
        MODE7_AbsSearch = 6,
        MODE8_LmtSearch = 7,
        MODE9_AbsSearch_Ref = 8,
        MODE10_AbsSearch_NegRef = 9,
        MODE11_LmtSearch_Ref = 10,
        MODE12_AbsSearchReFind = 11,
        MODE13_LmtSearchReFind = 12,
        MODE14_AbsSearchReFind_Ref = 13,
        MODE15_AbsSearchReFind_NegRef = 14,
        MODE16_LmtSearchReFind_Ref = 15
    }

    public enum Cia402HomeMode : uint
    {
        Cia402HomeMode1 = 101,
        Cia402HomeMode2 = 102,
        Cia402HomeMode3 = 103,
        Cia402HomeMode4 = 104,
        Cia402HomeMode5 = 105,
        Cia402HomeMode6 = 106,
        Cia402HomeMode7 = 107,
        Cia402HomeMode8 = 108,
        Cia402HomeMode9 = 109,
        Cia402HomeMode10 = 110,
        Cia402HomeMode11 = 111,
        Cia402HomeMode12 = 112,
        Cia402HomeMode13 = 113,
        Cia402HomeMode14 = 114,
        Cia402HomeMode15 = 115,
        Cia402HomeMode16 = 116,
        Cia402HomeMode17 = 117,
        Cia402HomeMode18 = 118,
        Cia402HomeMode19 = 119,
        Cia402HomeMode20 = 120,
        Cia402HomeMode21 = 121,
        Cia402HomeMode22 = 122,
        Cia402HomeMode23 = 123,
        Cia402HomeMode24 = 124,
        Cia402HomeMode25 = 125,
        Cia402HomeMode26 = 126,
        Cia402HomeMode27 = 127,
        Cia402HomeMode28 = 128,
        Cia402HomeMode29 = 129,
        Cia402HomeMode30 = 130,
        Cia402HomeMode31 = 131,
        Cia402HomeMode32 = 132,
        Cia402HomeMode33 = 133,
        Cia402HomeMode34 = 134,
        Cia402HomeMode35 = 135,
        Cia402HomeMode36 = 136,
        Cia402HomeMode37 = 137
    }

    public enum AxisState : uint
    {
        STA_AX_DISABLE = 0,
        STA_AX_READY = 1,
        STA_AX_STOPPING = 2,
        STA_AX_ERROR_STOP = 3,
        STA_AX_HOMING = 4,
        STA_AX_PTP_MOT = 5,
        STA_AX_CONTI_MOT = 6,
        STA_AX_SYNC_MOT = 7,
        STA_AX_EXT_JOG = 8,
        STA_AX_EXT_MPG = 9,
        STA_AX_PAUSE = 10,
        STA_AX_BUSY = 11,
        STA_AX_WAIT_DI = 12,
        STA_AX_WAIT_PTP = 13,
        STA_AX_WAIT_VEL = 14
    }
}
