//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatechApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreatechApp.Core.Resources.DialogTable", typeof(DialogTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor alarm is active.
        /// </summary>
        public static string AlarmActive {
            get {
                return ResourceManager.GetString("AlarmActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm summary saved.
        /// </summary>
        public static string AlarmSummarySave {
            get {
                return ResourceManager.GetString("AlarmSummarySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist in database.
        /// </summary>
        public static string alreadyexistindatabase {
            get {
                return ResourceManager.GetString("alreadyexistindatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to close the application ?.
        /// </summary>
        public static string AskConfirmCloseApp {
            get {
                return ResourceManager.GetString("AskConfirmCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to clear live sequence collection?.
        /// </summary>
        public static string AskConfirmDeleteLiveSeq {
            get {
                return ResourceManager.GetString("AskConfirmDeleteLiveSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Recipe ?.
        /// </summary>
        public static string AskConfirmDeleteRecipe {
            get {
                return ResourceManager.GetString("AskConfirmDeleteRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this User record ?.
        /// </summary>
        public static string AskConfirmDeleteUser {
            get {
                return ResourceManager.GetString("AskConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to End Current Lot:.
        /// </summary>
        public static string AskConfirmEndLot {
            get {
                return ResourceManager.GetString("AskConfirmEndLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to perform Initialization ?.
        /// </summary>
        public static string AskConfirmInit {
            get {
                return ResourceManager.GetString("AskConfirmInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to make changes to this parameter ?.
        /// </summary>
        public static string AskConfirmMakeChanges {
            get {
                return ResourceManager.GetString("AskConfirmMakeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to save the changes to alarm details ?.
        /// </summary>
        public static string AskConfirmSaveAlarmDetails {
            get {
                return ResourceManager.GetString("AskConfirmSaveAlarmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to save the changes to motion profile ?.
        /// </summary>
        public static string AskConfirmSaveMPChanges {
            get {
                return ResourceManager.GetString("AskConfirmSaveMPChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to save this parameter to current position ?.
        /// </summary>
        public static string AskConfirmSavePosition {
            get {
                return ResourceManager.GetString("AskConfirmSavePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to start this Lot :.
        /// </summary>
        public static string AskConfirmStartLot {
            get {
                return ResourceManager.GetString("AskConfirmStartLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the tower light setting ?.
        /// </summary>
        public static string AskConfirmUpdateTLSetting {
            get {
                return ResourceManager.GetString("AskConfirmUpdateTLSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable motors before exit program?.
        /// </summary>
        public static string AskOffActivedMotor {
            get {
                return ResourceManager.GetString("AskOffActivedMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to reset.
        /// </summary>
        public static string AskReset {
            get {
                return ResourceManager.GetString("AskReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to reset All Cleaning and Tool Life Counter ?.
        /// </summary>
        public static string AskResetAllCounter {
            get {
                return ResourceManager.GetString("AskResetAllCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to save the changes to.
        /// </summary>
        public static string AskSaveChange {
            get {
                return ResourceManager.GetString("AskSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to update.
        /// </summary>
        public static string AskUpdate {
            get {
                return ResourceManager.GetString("AskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Password not match.
        /// </summary>
        public static string BothPassNotMatch {
            get {
                return ResourceManager.GetString("BothPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Counter.
        /// </summary>
        public static string CleaningCounter {
            get {
                return ResourceManager.GetString("CleaningCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Live Seq Confirmation.
        /// </summary>
        public static string DeleteLiveSeqConfirmation {
            get {
                return ResourceManager.GetString("DeleteLiveSeqConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recipe Confirmation.
        /// </summary>
        public static string DeleteRecipeConfirmation {
            get {
                return ResourceManager.GetString("DeleteRecipeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Confirmation.
        /// </summary>
        public static string DeleteUserConfirmation {
            get {
                return ResourceManager.GetString("DeleteUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Lot.
        /// </summary>
        public static string EndLot {
            get {
                return ResourceManager.GetString("EndLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Stop.
        /// </summary>
        public static string Estop {
            get {
                return ResourceManager.GetString("Estop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Add New user.
        /// </summary>
        public static string FailAddNewUser {
            get {
                return ResourceManager.GetString("FailAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail delete user.
        /// </summary>
        public static string FaildeleteUser {
            get {
                return ResourceManager.GetString("FaildeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to insert Lot Info to Database.
        /// </summary>
        public static string FailInsertLot {
            get {
                return ResourceManager.GetString("FailInsertLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to reconnect.
        /// </summary>
        public static string FailReconnect {
            get {
                return ResourceManager.GetString("FailReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some TCP devices reconnect fail.
        /// </summary>
        public static string FailReconnectSomeTCP {
            get {
                return ResourceManager.GetString("FailReconnectSomeTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail update access control.
        /// </summary>
        public static string FailUpdateAccessCtrl {
            get {
                return ResourceManager.GetString("FailUpdateAccessCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail update user.
        /// </summary>
        public static string FailupdateUser {
            get {
                return ResourceManager.GetString("FailupdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HEX data format, please insert proper HEX.
        ///Example: A1 61 FF 97 .
        /// </summary>
        public static string HEXErrorContent {
            get {
                return ResourceManager.GetString("HEXErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal data format error.
        /// </summary>
        public static string HEXErrorTitle {
            get {
                return ResourceManager.GetString("HEXErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Completed.
        /// </summary>
        public static string HomeCompleted {
            get {
                return ResourceManager.GetString("HomeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure all Input is not empty.
        /// </summary>
        public static string InputEmpty {
            get {
                return ResourceManager.GetString("InputEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection Date. Start date is later than end date!.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection Date. Start Selection Date cannot larger than Selection End !.
        /// </summary>
        public static string InvalidSelectionDate {
            get {
                return ResourceManager.GetString("InvalidSelectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live sequence cleared.
        /// </summary>
        public static string LiveSeqCleared {
            get {
                return ResourceManager.GetString("LiveSeqCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live sequence saved.
        /// </summary>
        public static string LiveSeqSave {
            get {
                return ResourceManager.GetString("LiveSeqSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Make Sure Lot ID is not Empty.
        /// </summary>
        public static string LotIDEmpty {
            get {
                return ResourceManager.GetString("LotIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Initialization.
        /// </summary>
        public static string MachineInit {
            get {
                return ResourceManager.GetString("MachineInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Cleaning Counter.
        /// </summary>
        public static string MaxCleaningCounter {
            get {
                return ResourceManager.GetString("MaxCleaningCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module performance summary saved.
        /// </summary>
        public static string ModulePerfSaved {
            get {
                return ResourceManager.GetString("ModulePerfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Make Sure Machine Status is Idle before Close Application.
        /// </summary>
        public static string NotAllowToCloseApp {
            get {
                return ResourceManager.GetString("NotAllowToCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:
        ///Press Enter to continue. 
        ///Press ESC to cancel..
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Data saved.
        /// </summary>
        public static string OEEDataSaved {
            get {
                return ResourceManager.GetString("OEEDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Setting has been updated successfully.
        /// </summary>
        public static string OEESaved {
            get {
                return ResourceManager.GetString("OEESaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with new box.
        ///
        ///Notes:
        ///Press Enter to continue. 
        ///Press ESC to cancel..
        /// </summary>
        public static string OKResult {
            get {
                return ResourceManager.GetString("OKResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Make Sure Operator ID is not Empty.
        /// </summary>
        public static string OperatorIDEmpty {
            get {
                return ResourceManager.GetString("OperatorIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Result.
        /// </summary>
        public static string PassResult {
            get {
                return ResourceManager.GetString("PassResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name already exist in database.
        /// </summary>
        public static string ProductExist {
            get {
                return ResourceManager.GetString("ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe has been added successfully.
        /// </summary>
        public static string RecipeAdded {
            get {
                return ResourceManager.GetString("RecipeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe has been deleted successfully.
        /// </summary>
        public static string RecipeDeleted {
            get {
                return ResourceManager.GetString("RecipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Make Sure Recipe is not empty.
        /// </summary>
        public static string RecipeEmpty {
            get {
                return ResourceManager.GetString("RecipeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe has been updated successfully.
        /// </summary>
        public static string RecipeUpdated {
            get {
                return ResourceManager.GetString("RecipeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Restart The Application.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence status saved.
        /// </summary>
        public static string SeqStatusSaved {
            get {
                return ResourceManager.GetString("SeqStatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo is not ON.
        /// </summary>
        public static string ServoNotON {
            get {
                return ResourceManager.GetString("ServoNotON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo is not ON.
        /// </summary>
        public static string ServoOff {
            get {
                return ResourceManager.GetString("ServoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo is ON.
        /// </summary>
        public static string ServoOn {
            get {
                return ResourceManager.GetString("ServoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Saved!.
        /// </summary>
        public static string SettingSaved {
            get {
                return ResourceManager.GetString("SettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lot.
        /// </summary>
        public static string StartLot {
            get {
                return ResourceManager.GetString("StartLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Add New User.
        /// </summary>
        public static string SuccessAddNewUser {
            get {
                return ResourceManager.GetString("SuccessAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success delete User.
        /// </summary>
        public static string SuccessdeleteUser {
            get {
                return ResourceManager.GetString("SuccessdeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success update access control.
        /// </summary>
        public static string SuccessUpdateAccessCtrl {
            get {
                return ResourceManager.GetString("SuccessUpdateAccessCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success update User.
        /// </summary>
        public static string SuccessupdateUser {
            get {
                return ResourceManager.GetString("SuccessupdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run Completed.
        /// </summary>
        public static string TestRunCompleted {
            get {
                return ResourceManager.GetString("TestRunCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run Error :.
        /// </summary>
        public static string TestRunError {
            get {
                return ResourceManager.GetString("TestRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run mode not found.
        /// </summary>
        public static string TestRunNotFound {
            get {
                return ResourceManager.GetString("TestRunNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Life Counter.
        /// </summary>
        public static string ToolLifeCounter {
            get {
                return ResourceManager.GetString("ToolLifeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool life Max Counter.
        /// </summary>
        public static string ToolMaxCounter {
            get {
                return ResourceManager.GetString("ToolMaxCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo is not ON. Do you want to turn on servo?.
        /// </summary>
        public static string TurnOnServo {
            get {
                return ResourceManager.GetString("TurnOnServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not more than.
        /// </summary>
        public static string ValueNotMoreThan {
            get {
                return ResourceManager.GetString("ValueNotMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
