//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatechApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreatechApp.Core.Resources.InputTable", typeof(InputTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0100 | E Stop Button.
        /// </summary>
        public static string DI0100_E_StopBtn {
            get {
                return ResourceManager.GetString("DI0100_E_StopBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0101 | Air Pressure.
        /// </summary>
        public static string DI0101_AirPressure {
            get {
                return ResourceManager.GetString("DI0101_AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0102 | Vacuum.
        /// </summary>
        public static string DI0102_Vacuum {
            get {
                return ResourceManager.GetString("DI0102_Vacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0103 | Input Value 4.
        /// </summary>
        public static string DI0103_Input4 {
            get {
                return ResourceManager.GetString("DI0103_Input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0104 | Input Value 5.
        /// </summary>
        public static string DI0104_Input5 {
            get {
                return ResourceManager.GetString("DI0104_Input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0105 | Input Value 6.
        /// </summary>
        public static string DI0105_Input6 {
            get {
                return ResourceManager.GetString("DI0105_Input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0106 | Input Value 7.
        /// </summary>
        public static string DI0106_Input7 {
            get {
                return ResourceManager.GetString("DI0106_Input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0107 | Input Value 8.
        /// </summary>
        public static string DI0107_Input8 {
            get {
                return ResourceManager.GetString("DI0107_Input8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I0108 | Input Value 9.
        /// </summary>
        public static string DI0108_Input9 {
            get {
                return ResourceManager.GetString("DI0108_Input9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test | Sample Sequence Gripper Work.
        /// </summary>
        public static string DI0109_Test_IsGripperWork {
            get {
                return ResourceManager.GetString("DI0109_Test_IsGripperWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test | Sample Sequence Gripper Rest.
        /// </summary>
        public static string DI0110_Test_IsGripperRest {
            get {
                return ResourceManager.GetString("DI0110_Test_IsGripperRest", resourceCulture);
            }
        }
    }
}
