//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatechApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OutputTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreatechApp.Core.Resources.OutputTable", typeof(OutputTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O0100 | Buzzer   .
        /// </summary>
        public static string DO0100_Buzzer {
            get {
                return ResourceManager.GetString("DO0100_Buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O0101 | Red Tower Light.
        /// </summary>
        public static string DO0101_RedTowerLight {
            get {
                return ResourceManager.GetString("DO0101_RedTowerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O0102 | Amber Tower Light.
        /// </summary>
        public static string DO0102_AmberTowerLight {
            get {
                return ResourceManager.GetString("DO0102_AmberTowerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O0103 | Green Tower Light.
        /// </summary>
        public static string DO0103_GreenTowerLight {
            get {
                return ResourceManager.GetString("DO0103_GreenTowerLight", resourceCulture);
            }
        }
    }
}
